### ISSUE TITLE
Do you add a log printing example of curl -v?

### ISSUE THREAD

**Issue by obelieve** [robertying/AndroidCurlExample#3]

**Comment by robertying** [comment]
See https://github.com/robertying/AndroidCurlExample/commit/c1dbebfa07e90a194eab3140b2ee9d17bda752a6.

Additional info can be found in [curl_version_info](https://curl.se/libcurl/c/curl_version_info.html).

**Comment by obelieve** [comment]
> See [c1dbebf](https://github.com/robertying/AndroidCurlExample/commit/c1dbebfa07e90a194eab3140b2ee9d17bda752a6).
> 
> Additional info can be found in [curl_version_info](https://curl.se/libcurl/c/curl_version_info.html).

Hi. Maybe it's not a good description, but I'd like to say something like this verbose info : curl -v http://www.google.com

**Comment by obelieve** [comment]
> See [c1dbebf](https://github.com/robertying/AndroidCurlExample/commit/c1dbebfa07e90a194eab3140b2ee9d17bda752a6).
> 
> Additional info can be found in [curl_version_info](https://curl.se/libcurl/c/curl_version_info.html).

Hi. Maybe it's not a good description, but I'd like to say something like this verbose info : curl -v https://www.google.com

**Comment by obelieve** [comment]
> See [c1dbebf](https://github.com/robertying/AndroidCurlExample/commit/c1dbebfa07e90a194eab3140b2ee9d17bda752a6).
> 
> Additional info can be found in [curl_version_info](https://curl.se/libcurl/c/curl_version_info.html).

Thank you for your reply, but I'd like to say something like this verbose info : curl -v https://www.google.com

**Comment by robertying** [comment]
Please check https://curl.se/libcurl/c/CURLOPT_VERBOSE.html

**Comment by obelieve** [comment]
> Please check https://curl.se/libcurl/c/CURLOPT_VERBOSE.html

Is there an example to show that the one I tried doesn't work，not return verbose info
